openapi: 3.0.1
paths:
  /:
    put:
      responses:
        '200':
          description: default OK response
          headers:
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt:
            - ApiToNewCodespaceStateMachineRole
            - Arn
        httpMethod: POST
        type: aws
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:states:action/StartSyncExecution
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: '''*'''
            responseTemplates:
              application/json: $util.parseJson($input.json('$.output'))
        requestTemplates:
          application/json:
            Fn::Sub: |-
              {
                "name": "$context.requestId",
                "stateMachineArn": "${NewCodespaceStateMachine}"
              }
    get:
      responses:
        '200':
          description: default OK response
          headers:
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt:
            - ApiToCodespaceDetailsStateMachineRole
            - Arn
        httpMethod: POST
        type: aws
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:states:action/StartSyncExecution
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: '''*'''
            responseTemplates:
              application/json: $util.parseJson($input.json('$.output'))
        requestTemplates:
          application/json:
            Fn::Sub: |-
              {
                "input": "{\"queryParams\":{#foreach($param in $input.params().querystring.keySet())\"$param\":\"$util.escapeJavaScript($input.params().querystring.get($param))\"#if($foreach.hasNext),#end#end}}",
                "name": "$context.requestId",
                "stateMachineArn": "${CodespaceDetailsStateMachine}"
              }
    post:
      responses:
        '200':
          description: OK response
          headers:
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt:
            - ApiToCreateComposableStateMachineRole
            - Arn
        httpMethod: POST
        type: aws
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:states:action/StartSyncExecution
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: '''*'''
            responseTemplates:
              application/json: $util.parseJson($input.json('$.output'))
        requestTemplates:
          application/json:
            Fn::Sub: |-
              {
                "input": "{\"body\":$util.escapeJavaScript($input.body)}",
                "name": "$context.requestId",
                "stateMachineArn": "${CreateComposableStateMachine}"
              }
